#include <18F2580.h>
#device ADC=8

#FUSES NOWDT                    //No Watch Dog Timer
#FUSES NOBROWNOUT               //No brownout reset

// THROTTLE AND BRAKE PEDAL SENSORS CALIBRATION DATA
#define SECURITY_MARGIN 5

// ACC1 REMEMBER: SUBSTRACT 3 TO THE MIN AND ADD 3 TO THE MAX !
#define PRESET_ACC1_MIN 101 
#define PRESET_ACC1_MAX 174

// ACC2 REMEMBER: SUBSTRACT 3 TO THE MIN AND ADD 3 TO THE MAX !
#define PRESET_ACC2_MIN 130
#define PRESET_ACC2_MAX 201

// ACC3 REMEMBER: SUBSTRACT 3 TO THE MIN AND ADD 3 TO THE MAX !
#define PRESET_ACC3_MIN 31
#define PRESET_ACC3_MAX 166

// BRK REMEMBER: SUBSTRACT 3 TO THE MIN AND ADD 3 TO THE MAX !
#define PRESET_BRK_MIN 25
#define PRESET_BRK_MAX 88

#use delay(crystal=20000000)

